name: Build and Deploy
on:
  push:
    branches:
    - 'VuNB'

jobs:

  data-validation:
      name: Data Validation
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade "pip<20"
          pip install -r requirement.txt
      - name: Rasa Data Validation
        working-directory: ${{ github.workspace }}
        run: |
          rasa data validate --debug

  training-testing:
      name: Train model Rasa
      runs-on: ubuntu-latest
      needs: [data-validation]
      steps:
      - uses: actions/checkout@v1
      - name: set_training
        run: echo "RUN_TRAINING=true"  >> $GITHUB_ENV
      - name: Set up Python 3.7
        if: env.RUN_TRAINING == 'true'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        if: env.RUN_TRAINING == 'true'
        run: |
            python -m pip install --upgrade "pip<20"
            pip install -r requirement.txt
      - name: Train Model
        if: env.RUN_TRAINING == 'true'
        working-directory: ${{ github.workspace }}
        run: |
          rasa train
      - name: Upload model
        if: |
            env.RUN_TRAINING == 'true'
        uses: actions/upload-artifact@main
        with:
          name: model
          path: models
  print:
      name: Print hihihi
      runs-on: ubuntu-latest
      needs: [data-validation]
      run: echo "hihihi"
