name: Build and Deploy
on: [pull_request]

jobs:

  data-validation:
      name: Data Validation
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade "pip<20"
          pip install -r requirement.txt
      - name: Rasa Data Validation
        working-directory: ${{ github.workspace }}
        run: |
          rasa data validate --debug

  training-testing:
      name: Testing Stories
      runs-on: ubuntu-latest
      needs: [data-validation]
      steps:
      - uses: actions/checkout@v1
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: set_training
        if: |
            contains(  steps.files.outputs.all, 'data/' ) 
            || contains(  steps.files.outputs.all, 'config.yml' ) 
            || contains(  steps.files.outputs.all, 'domain.yml' )
        run: echo "RUN_TRAINING=true"  >> $GITHUB_ENV
      - name: Set up Python 3.7
        if: env.RUN_TRAINING == 'true'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        if: env.RUN_TRAINING == 'true'
        run: |
            python -m pip install --upgrade "pip<20"
            pip install -r requirement.txt
      - name: Train Model
        if: env.RUN_TRAINING == 'true'
        working-directory: ${{ github.workspace }}
        run: |
          rasa train
      - name: Upload model
        if: |
            github.ref == 'refs/heads/main'
            && env.RUN_TRAINING == 'true'
        uses: actions/upload-artifact@main
        with:
          name: model
          path: models